# DX 601 Week 9 Homework

## Introduction

In this homework, you will practice basic operations with vectors and matrices.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [1]:
import math
import sys

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

## Problems

### Problem 1

Set `p1` to the vector from calculating $[0.0, 0.3, 0.65] + [2.2, 6.2, 0.35]$.

In [58]:
# YOUR CHANGES HERE
x = np.array([0.0, 0.3, 0.65])
y = np.array([2.2, 6.2, 0.35])
p1 = x + y

In [59]:
p1

array([2.2, 6.5, 1. ])

### Problem 2

Set `p2` to the magnitude of the vector $[1, 3, 6]$?

In [61]:
# YOUR CHANGES HERE
mag = np.array([1,3,6])
p2 = np.linalg.norm(mag)

In [62]:
p2

np.float64(6.782329983125268)

### Problem 3

Set `p3` to the magnitude of the vector `q3`.

In [7]:
# DO NOT CHANGE

q3 = np.asarray([5.2, 5.9, 9.1, 4.3, 2.9])
q3

array([5.2, 5.9, 9.1, 4.3, 2.9])

In [63]:
# YOUR CHANGES HERE

p3 = np.linalg.norm(q3)

In [64]:
p3

np.float64(13.098091464026353)

### Problem 4

Set `p4` to the dot product of $[2, 0, 3]$ and $[0, 4, 1]$.

Hint: this should feel like a really easy case to just do in your head.

In [65]:
# YOUR CHANGES HERE
x = [2,0,3]
y = [0,4,1]
p4 = np.dot(x,y)

In [66]:
p4

np.int64(3)

### Problem 5

Set `p5` to the element-wise product of `u5` and `v5`.

Hint: the default behavior of mathematical operations on NumPy arrays is to calculate on an element-wise basis.

In [12]:
# DO NOT CHANGE

u5 = np.asarray([5, 5, 5])
u5

array([5, 5, 5])

In [13]:
# DO NOT CHANGE

v5 = np.asarray([1, 6, 2])
v5

array([1, 6, 2])

In [67]:
# YOUR CHANGES HERE

p5 = u5 * v5

In [68]:
p5

array([ 5, 30, 10])

### Problem 6

Set `p6` to the dot product of `u6` and `v6`.

In [16]:
# DO NOT CHANGE

u6 = np.asarray([2.03, 0.40, 1.35, 9.26, 4.23])
u6

array([2.03, 0.4 , 1.35, 9.26, 4.23])

In [17]:
# DO NOT CHANGE

v6 = np.asarray([1.32, 0.96, 2.35, 1.23, 0.25])
v6

array([1.32, 0.96, 2.35, 1.23, 0.25])

In [69]:
# YOUR CHANGES HERE

p6 = np.dot(u6, v6)

In [70]:
p6

np.float64(18.6834)

### Problem 7

Set `p7` to the cosine similarity of `u7` and `v7`.

In [20]:
# DO NOT CHANGE

u7 = np.asarray([1, 1, 1, 1])
u7

array([1, 1, 1, 1])

In [21]:
# DO NOT CHANGE

v7 = np.asarray([0, 2, 0, 0])
v7

array([0, 2, 0, 0])

In [73]:
# YOUR CHANGES HERE

p7 = np.dot(u7,v7) / (np.linalg.norm(u7) * np.linalg.norm(v7))

In [74]:
p7

np.float64(0.5)

### Problem 8

Set `p8` to the vector $[x, y]$ corresponding to the polar coordinates $(r, \theta) = (1, 1)$.

In [75]:
# YOUR CHANGES HERE

p8 = np.array([np.cos(1), np.sin(1)])

In [76]:
p8

array([0.54030231, 0.84147098])

### Problem 9

Set `p9` to the scalar-vector product $3.1 \cdot [1.31, 2.06, 9.56, 1.79]$.

In [80]:
# YOUR CHANGES HERE
q9 = np.array([1.31, 2.06, 9.56, 1.70])
scalar = 3.1
p9 = scalar * q9

In [81]:
p9

array([ 4.061,  6.386, 29.636,  5.27 ])

### Problem 10

Set `p10` to be a unit vector in the same direction as $[1.31, 2.13, -0.92]$.


In [82]:
# YOUR CHANGES HERE
q10 = [1.31, 2.13, -0.92]
p10 = q10 / np.linalg.norm(q10)

In [83]:
p10

array([ 0.49165501,  0.79940853, -0.34528444])

### Problem 11

Set `p11` to be the first of the following vectors that is orthogonal to $[1, 0, 0]$.

* $[1, 1, 1]$
* $[0.5, 1, 1]$
* $[0, 1, 1]$
* $[1, 0, 1]$

In [87]:
x = np.array([1,0,0])
y = np.array([1,1,1])
z = np.array([0.5,1,1])
a = np.array([0,1,1])
b = np.array([1,0,1])
np.dot(x,a)
p11 = a

In [88]:
p11

array([0, 1, 1])

### Problem 12

Set `p12` to the first vector in the following list which is linearly dependent on the previous vectors.

* $[0, 1, 1]$
* $[0, 0, 1]$
* $[1, 0, 1]$
* $[1, 1, 1]$

In [108]:
# YOUR CHANGES HERE
qx = [0,1,1]
qy = [0,0,1]
qz = [1,0,1]
qa = [1,1,1]
p12 = qa

In [109]:
p12

[1, 1, 1]

### Problem 13

Set `p13` to the $3 \times 3$ identity matrix.

In [112]:
# YOUR CHANGES HERE

p13 = np.identity(3)

In [113]:
p13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Problem 14

Set `p14` to the x intercept of the equation $3y + 5x = 2$.

In [114]:
# YOUR CHANGES HERE

p14 = 2/5

In [115]:
p14

0.4

### Problem 15

Given the dictionary of phrases and vectors in `q15`, set `p15` to the phrase (key) whose vector has the highest cosine similarity with $[0.1, 0.5, 0.2]$.

In [38]:
# DO NOT CHANGE

q15 = {
    "cat": [0.1, 0.6, 0.3],
    "dog": [0.2, 0.5, 0.1],
    "elephant": [-0.3, 0.2, 0.5],
    "giraffe": [-0.4, 0.3, -0.1],
    "lion": [0.1, 0.7, 0.2]
}
q15 = {k: np.asarray(v) for k, v in q15.items()}

q15

{'cat': array([0.1, 0.6, 0.3]),
 'dog': array([0.2, 0.5, 0.1]),
 'elephant': array([-0.3,  0.2,  0.5]),
 'giraffe': array([-0.4,  0.3, -0.1]),
 'lion': array([0.1, 0.7, 0.2])}

In [119]:
# YOUR CHANGES HERE
target = np.array([0.1, 0.5, 0.2])
max_similarity = -1
bestkey = None

for key, value in q15.items():
    similarity = np.dot(target, value) / (np.linalg.norm(target) * np.linalg.norm(value))
    if similarity > max_similarity:
        max_similarity = similarity
        bestkey = key
    
p15 = bestkey

In [120]:
p15

'cat'

### Problem 16

Rescale the vectors $[2, 0, 0, 0]$ and $[0, 1, 1, 1]$ so that they are orthonormal.

Save the first rescaled vector in `p16a` and the second rescaled vector in `p16b`.

In [126]:
# YOUR CHANGES HERE
v1 = np.array([2,0,0,0])
v2 = np.array([0,1,1,1])
p16a = v1 / np.linalg.norm(v1)

In [127]:
p16a

array([1., 0., 0., 0.])

In [128]:
# YOUR CHANGES HERE

p16b = v2 / np.linalg.norm(v2)

In [129]:
p16b

array([0.        , 0.57735027, 0.57735027, 0.57735027])

### Problem 17

Set `p17` to the result of the matrix multiplication of `x17` by `y17`.

Hint: NumPy has a function for matrix multiplication, and also overrides the Python @ operator.

In [45]:
# DO NOT CHANGE

x17 = np.array([[0.2, 3.1, 0.6], [-2.9, 2.3, 4.2], [3.0, 4.5, 1.7]])
x17

array([[ 0.2,  3.1,  0.6],
       [-2.9,  2.3,  4.2],
       [ 3. ,  4.5,  1.7]])

In [46]:
# DO NOT CHANGE

y17 = np.array([[1, 2, 3], [6, 5, 4], [7, 8, 9]])
y17

array([[1, 2, 3],
       [6, 5, 4],
       [7, 8, 9]])

In [130]:
# YOUR CHANGES HERE

p17 = x17@y17

In [131]:
p17

array([[23. , 20.7, 18.4],
       [40.3, 39.3, 38.3],
       [41.9, 42.1, 42.3]])

### Problem 18

Set `p18` to the angle $\theta$ between the vectors in `u18` and `v18`.
Use the measure of the angle in radians, not degrees.

Hint: you can use the cosine similarity to calculate $\mathrm{cos}~\theta$.
The inverse cosine function to recover the measure of the angle is often called the arc cosine, and both the math and NumPy modules use this for their naming.

In [49]:
# DO NOT CHANGE

u18 = np.asarray([0.3, 0.2, 0.9, -0.4])
u18

array([ 0.3,  0.2,  0.9, -0.4])

In [50]:
# DO NOT CHANGE

v18 = np.asarray([-0.1, 0.3, 0.6, -0.2])
v18

array([-0.1,  0.3,  0.6, -0.2])

In [132]:
# YOUR CHANGES HERE
dot = np.dot(u18, v18) / (np.linalg.norm(u18) * np.linalg.norm(v18))

p18 = np.arccos(dot)

In [133]:
p18

np.float64(0.5023368499123668)

### Problem 19

Set `p19` to be the largest magnitude vector from the following list.

* $[0.1, 0.3, 0.9, -0.8]$
* $[0.2, 0.2, 0.7, 0.6]$
* $[-0.2, 0.2, 0.7, -0.6]$
* $[1.0, 1.0, 0.4, 0.5]$

In [140]:
# YOUR CHANGES HERE
q19a = [0.1,0.3,0.9,-0.8]
q19b = [0.2, 0.2, 0.7, 0.6]
q19c = [-0.2, 0.2, 0.7, -0.6]
q19d = [1.0, 1.0, 0.4, 0.5]
p19 = np.linalg.norm(q19d)

In [141]:
p19

np.float64(1.5524174696260025)

### Problem 20

Set `p20` to $3 \mathbf{x} + 5$ where $x$ is stored in `x20`.

In [55]:
# DO NOT CHANGE

x20 = np.asarray([0.2, 0.5, -0.3, 0.8])

In [142]:
# YOUR CHANGES HERE

p20 = 3 * x20 + 5

In [143]:
p20

array([5.6, 6.5, 4.1, 7.4])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

NONE